default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :test do |options|
    # add actions here: https://docs.fastlane.tools/actions
    puts "Performing beta distribution using fastlane"
    puts "Following options were passed as arguments to the lane:"
    options.each do |key, value|
      puts "#{key}:#{value}"
    end
    puts "Environment variables:"
    sh("env")
  end
end
